### ISSUE TITLE
using env variable DD_SERVICE instead of a tag named service 

### ISSUE THREAD

**Issue by maxday** [DataDog/datadog-cloudformation-macro#13]
Hi !
First, thanks for this nice macro 💯 
I've noticed that the service name is taken from a 'service' tag instead of the 'classical' env variable DD_SERVICE.
Is there any reason for that, if not, I would be glad to create a PR for this.
Please let me know !
Thanks !

**Comment by tianchu** [comment]
@maxday Sorry for the super late response, we didn't set up proper notification for github issues on our side, apologies! The reason is that Lambda tags already automatically get applied to the `aws.lambda.*` metrics as a default behavior of the Datadog AWS integration, which makes correlation between metrics, traces and logs easier (all defined by one tag). That said, it is technically possible for us to apply certain `DD_XXX` environment variables to `aws.lambda.*` metrics as tags too, so we may consider supporting both tags and environment variables eventually.
